# Generated by Django 5.0 on 2024-01-06 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Enter a valid email address.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='type_value',
            field=models.CharField(choices=[('V', 'vendor'), ('C', 'customer')], max_length=10),
        ),
    ]
