version: '3.8'

services:
  timescaledb:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: timescaledb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432
